development:
  adapter: postgresql
  database: ilan_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: ilan_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ilan_production
  pool: 5
  timeout: 5000